### ISSUE TITLE
Problems loading the gem inside Github Pages

### ISSUE THREAD

**Issue by arthuralvim** [benbalter/jekyll-bootstrap-sass#3]
Hi, Ben!

I've been using your gem and it facilitates a lot to integrate bootstrap-sass to jekyll websites.

Locally, the package works alright and here's the last builts of the CI to prove no error was raised.
https://travis-ci.org/dojodocirculo/dojodocirculo.github.io

But when building the site with Github pages it gives me this message:

Your site is having problems building: Your SCSS file assets/css/styles.scss has an error on line 8: File to import not found or unreadable: bootstrap. Load paths: _sass /hoosegow/.bundle/ruby/2.3.0/gems/jekyll-theme-primer-0.1.8/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/.

I believe I have found a small problem with the loading of the modules in Github Pages.

Here's the site I'm trying to build.
https://github.com/dojodocirculo/dojodocirculo.github.io

Is there any example of this gem being used with Github Pages?

**Comment by benbalter** [comment]
You can see the list of themes supported by GitHub Pages at https://pages.github.com/versions/.

**Comment by BrOrlandi** [comment]
Hi, Ben!
I also have this problem and I don't understand how to solve it.
I don't have the `theme` in the `_config.yml`, I removed because I'm using my own theme.
Can you tell how do I fix this problem?

Thank you!

**Comment by benbalter** [comment]
> You can see the list of themes supported by GitHub Pages at https://pages.github.com/versions/.

Currently the plugin is not supported on GitHub Pages.
